# -*- coding: utf-8 -*-
# Generated by DjangoQ 1.10.6 on 2018-05-14 02:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128, verbose_name='标题')),
                ('comment', models.TextField(verbose_name='评论')),
                ('primary', models.TextField(default='默认快照', verbose_name='快照')),
                ('date', models.DateField(auto_now_add=True)),
                ('img', models.FileField(default='', upload_to='static/blog/home/imgs/upload/', verbose_name='照片')),
                ('img_name', models.CharField(default='', max_length=16, verbose_name='图片名称')),
            ],
            options={
                'verbose_name_plural': '博客',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='正文')),
            ],
            options={
                'verbose_name_plural': '详细内容',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.Details', verbose_name='更多'),
        ),
    ]
