# -*- coding: utf-8 -*-
# Generated by DjangoQ 1.10.6 on 2018-05-16 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='primary',
            field=models.TextField(default='默认快照', max_length=35, verbose_name='快照'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(max_length=17, verbose_name='标题'),
        ),
    ]
