# -*- coding: utf-8 -*-
# Generated by DjangoQ 1.10.6 on 2018-05-16 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_auto_20180516_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='primary',
            field=models.TextField(default='默认快照', max_length=42, verbose_name='快照'),
        ),
    ]
