# -*- coding: utf-8 -*-
# Generated by DjangoQ 1.10.6 on 2018-05-17 07:02
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_auto_20180516_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文'),
        ),
    ]
