# -*- coding: utf-8 -*-
# Generated by DjangoQ 1.10.6 on 2018-05-17 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_auto_20180517_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comment',
            field=models.TextField(default='我是评论', verbose_name='评论'),
        ),
    ]
