# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-13 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_auto_20180517_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='好友姓名')),
                ('content', models.CharField(max_length=160, verbose_name='留言内容')),
                ('userimg', models.CharField(max_length=32, verbose_name='头像')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
